# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/eventchain',
                'doc_host': 'https://tkanngiesser.github.io',
                'git_url': 'https://github.com/tkanngiesser/eventchain',
                'lib_path': 'eventchain'},
  'syms': {'eventchain.core': {'eventchain.core.foo': ('core.html#foo', 'eventchain/core.py')}}}
